// emulate the browser
### GET /

GET http://localhost:8000

### POST / register

POST http://localhost:8000/auth/register
Content-Type: application/json

{
  "username":"bob",
  "password":"password"
}


### Login a user POST /AUTH/LOGIN

POST http://localhost:8000/auth/login
Content-Type: application/json

{
  "username":"bob",
  "password":"password"
}



